"""empty message

Revision ID: 102af525bd38
Revises: 40cfece36a68
Create Date: 2021-01-15 17:28:42.380586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102af525bd38'
down_revision = '40cfece36a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
