"""empty message

Revision ID: 2fcb35c81dc7
Revises: 5b78dc2bf4c5
Create Date: 2021-01-16 18:44:21.935201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcb35c81dc7'
down_revision = '5b78dc2bf4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'band')
    op.drop_column('Show', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('end_time', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('band', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
