"""empty message

Revision ID: 323e72d861e8
Revises: f19b4e8b16ee
Create Date: 2021-01-12 20:15:00.237456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323e72d861e8'
down_revision = 'f19b4e8b16ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.String(length=60), nullable=True),
    sa.Column('end_time', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent_description', sa.String(length=250), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'past_shows_count')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('Show')
    op.drop_table('Genre')
    # ### end Alembic commands ###
