"""empty message

Revision ID: 45aa23a54155
Revises: 323e72d861e8
Create Date: 2021-01-15 13:01:09.184486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45aa23a54155'
down_revision = '323e72d861e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Genre', 'Venue', ['venue_id'], ['id'])
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_column('Genre', 'venue_id')
    # ### end Alembic commands ###
