"""empty message

Revision ID: 498c0b822ffe
Revises: 0c9f43118e8b
Create Date: 2021-01-19 20:01:21.501600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c0b822ffe'
down_revision = '0c9f43118e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
