"""empty message

Revision ID: 531276860f1d
Revises: de559457f044
Create Date: 2021-01-19 23:10:51.085358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531276860f1d'
down_revision = 'de559457f044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
